### ISSUE TITLE
Picture not filled correctly

### ISSUE THREAD

**Issue by Szymoneko1** [4UPanElektryk/Random_Image_Generator#1]
![image](https://user-images.githubusercontent.com/115813099/195898099-a5815e13-51dc-45f1-9ba6-6f770d1200bd.png)
seed 2137
height 1920
width 1080
sequential averaged random

**Comment by 4UPanElektryk** [comment]
Which Version

**Comment by 4UPanElektryk** [comment]
Could not Recreate
